/**
 * src/lib/soma-ai/system-map.generated.ts
 *
 * GENERATED FILE — DO NOT EDIT BY HAND.
 * Regenerate with: npm run generate:system-map
 *
 * A map of every page in Bidii, derived from the Next.js route tree so it can
 * never drift from the real UI. Soma AI quotes from this when answering
 * "where do I find X" so it names only pages that actually exist.
 *
 * Generated from 187 pages.
 */

export interface SystemMapRoute {
  route: string;
  area: "principal" | "teacher" | "staff" | "parent" | "student";
  label: string;
  section: string;
  /** Detail pages opened by selecting a record, not from a menu. */
  detail: boolean;
}

export const SYSTEM_MAP: SystemMapRoute[] = [
  { route: "/parent", area: "parent", label: "Dashboard (home)", section: "/parent", detail: false },
  { route: "/parent/achievements", area: "parent", label: "Achievements", section: "/parent", detail: false },
  { route: "/parent/attendance", area: "parent", label: "Attendance", section: "/parent", detail: false },
  { route: "/parent/behaviour", area: "parent", label: "Behaviour", section: "/parent", detail: false },
  { route: "/parent/calendar", area: "parent", label: "Calendar", section: "/parent", detail: false },
  { route: "/parent/diary", area: "parent", label: "Diary", section: "/parent", detail: false },
  { route: "/parent/fees", area: "parent", label: "Fees", section: "/parent", detail: false },
  { route: "/parent/messages", area: "parent", label: "Messages", section: "/parent", detail: false },
  { route: "/parent/notifications", area: "parent", label: "Notifications", section: "/parent", detail: false },
  { route: "/parent/profile", area: "parent", label: "Profile", section: "/parent", detail: false },
  { route: "/parent/results", area: "parent", label: "Results", section: "/parent", detail: false },
  { route: "/principal", area: "principal", label: "Dashboard (home)", section: "/principal", detail: false },
  { route: "/principal/academics", area: "principal", label: "Academics", section: "/principal", detail: false },
  { route: "/principal/accommodation", area: "principal", label: "Accommodation", section: "/principal", detail: false },
  { route: "/principal/accommodation/allocations", area: "principal", label: "Allocations", section: "/principal/accommodation", detail: false },
  { route: "/principal/accommodation/analytics", area: "principal", label: "Analytics", section: "/principal/accommodation", detail: false },
  { route: "/principal/accommodation/dormitories", area: "principal", label: "Dormitories", section: "/principal/accommodation", detail: false },
  { route: "/principal/accommodation/dormitories/[dormId]", area: "principal", label: "Dorm detail", section: "/principal/accommodation", detail: true },
  { route: "/principal/accommodation/inspections", area: "principal", label: "Inspections", section: "/principal/accommodation", detail: false },
  { route: "/principal/accommodation/management", area: "principal", label: "Management", section: "/principal/accommodation", detail: false },
  { route: "/principal/accommodation/overview", area: "principal", label: "Overview", section: "/principal/accommodation", detail: false },
  { route: "/principal/accommodation/reports", area: "principal", label: "Reports", section: "/principal/accommodation", detail: false },
  { route: "/principal/accommodation/settings", area: "principal", label: "Settings", section: "/principal/accommodation", detail: false },
  { route: "/principal/administration", area: "principal", label: "Administration", section: "/principal", detail: false },
  { route: "/principal/assessments", area: "principal", label: "Assessments", section: "/principal", detail: false },
  { route: "/principal/assessments/dashboard", area: "principal", label: "Dashboard", section: "/principal/assessments", detail: false },
  { route: "/principal/assessments/dept-analytics", area: "principal", label: "Dept Analytics", section: "/principal/assessments", detail: false },
  { route: "/principal/assessments/exam-setup", area: "principal", label: "Exam Setup", section: "/principal/assessments", detail: false },
  { route: "/principal/assessments/forms/[form]", area: "principal", label: "Form detail", section: "/principal/assessments", detail: true },
  { route: "/principal/assessments/marksheet", area: "principal", label: "Marksheet", section: "/principal/assessments", detail: false },
  { route: "/principal/assessments/pathway-weights", area: "principal", label: "Pathway Weights", section: "/principal/assessments", detail: false },
  { route: "/principal/assessments/periods", area: "principal", label: "Periods", section: "/principal/assessments", detail: false },
  { route: "/principal/assessments/report-cards", area: "principal", label: "Report Cards", section: "/principal/assessments", detail: false },
  { route: "/principal/assessments/report-cards-cbe", area: "principal", label: "Report Cards CBE", section: "/principal/assessments", detail: false },
  { route: "/principal/assessments/report-cards/[studentId]", area: "principal", label: "Student detail", section: "/principal/assessments", detail: true },
  { route: "/principal/assessments/staff-performance", area: "principal", label: "Staff Performance", section: "/principal/assessments", detail: false },
  { route: "/principal/attendance", area: "principal", label: "Attendance", section: "/principal", detail: false },
  { route: "/principal/attendance/absent-today", area: "principal", label: "Absent Today", section: "/principal/attendance", detail: false },
  { route: "/principal/calendar", area: "principal", label: "Calendar", section: "/principal", detail: false },
  { route: "/principal/class-profiles", area: "principal", label: "Class Profiles", section: "/principal", detail: false },
  { route: "/principal/class-profiles/[classId]", area: "principal", label: "Class detail", section: "/principal/class-profiles", detail: true },
  { route: "/principal/class-profiles/form/[form]", area: "principal", label: "Form detail", section: "/principal/class-profiles", detail: true },
  { route: "/principal/classes", area: "principal", label: "Classes", section: "/principal", detail: false },
  { route: "/principal/communication", area: "principal", label: "Communication", section: "/principal", detail: false },
  { route: "/principal/communication/exam-results", area: "principal", label: "Exam Results", section: "/principal/communication", detail: false },
  { route: "/principal/communication/groups", area: "principal", label: "Groups", section: "/principal/communication", detail: false },
  { route: "/principal/communication/templates", area: "principal", label: "Templates", section: "/principal/communication", detail: false },
  { route: "/principal/departments", area: "principal", label: "Departments", section: "/principal", detail: false },
  { route: "/principal/finance", area: "principal", label: "Finance", section: "/principal", detail: false },
  { route: "/principal/history", area: "principal", label: "History", section: "/principal", detail: false },
  { route: "/principal/library", area: "principal", label: "Library", section: "/principal", detail: false },
  { route: "/principal/people", area: "principal", label: "People", section: "/principal", detail: false },
  { route: "/principal/profile", area: "principal", label: "Profile", section: "/principal", detail: false },
  { route: "/principal/records", area: "principal", label: "Records", section: "/principal", detail: false },
  { route: "/principal/records/achievements", area: "principal", label: "Achievements", section: "/principal/records", detail: false },
  { route: "/principal/records/discipline", area: "principal", label: "Discipline", section: "/principal/records", detail: false },
  { route: "/principal/records/discipline/[id]", area: "principal", label: " detail", section: "/principal/records", detail: true },
  { route: "/principal/reports", area: "principal", label: "Reports", section: "/principal", detail: false },
  { route: "/principal/results", area: "principal", label: "Results", section: "/principal", detail: false },
  { route: "/principal/settings", area: "principal", label: "Settings", section: "/principal", detail: false },
  { route: "/principal/staff", area: "principal", label: "Staff", section: "/principal", detail: false },
  { route: "/principal/staff-roles", area: "principal", label: "Staff Roles", section: "/principal", detail: false },
  { route: "/principal/staff/roles", area: "principal", label: "Roles", section: "/principal/staff", detail: false },
  { route: "/principal/students", area: "principal", label: "Students", section: "/principal", detail: false },
  { route: "/principal/students/[id]", area: "principal", label: " detail", section: "/principal/students", detail: true },
  { route: "/principal/subjects", area: "principal", label: "Subjects", section: "/principal", detail: false },
  { route: "/principal/timetable", area: "principal", label: "Timetable", section: "/principal", detail: false },
  { route: "/principal/timetable/builder", area: "principal", label: "Builder", section: "/principal/timetable", detail: false },
  { route: "/principal/timetable/generate", area: "principal", label: "Generate", section: "/principal/timetable", detail: false },
  { route: "/principal/timetable/preferences", area: "principal", label: "Preferences", section: "/principal/timetable", detail: false },
  { route: "/principal/timetable/requirements", area: "principal", label: "Requirements", section: "/principal/timetable", detail: false },
  { route: "/principal/timetable/settings", area: "principal", label: "Settings", section: "/principal/timetable", detail: false },
  { route: "/principal/timetable/template", area: "principal", label: "Template", section: "/principal/timetable", detail: false },
  { route: "/principal/timetable/versions", area: "principal", label: "Versions", section: "/principal/timetable", detail: false },
  { route: "/staff", area: "staff", label: "Dashboard (home)", section: "/staff", detail: false },
  { route: "/staff/academics", area: "staff", label: "Academics", section: "/staff", detail: false },
  { route: "/staff/accommodation", area: "staff", label: "Accommodation", section: "/staff", detail: false },
  { route: "/staff/accommodation/allocate", area: "staff", label: "Allocate", section: "/staff/accommodation", detail: false },
  { route: "/staff/accommodation/inspections", area: "staff", label: "Inspections", section: "/staff/accommodation", detail: false },
  { route: "/staff/administration", area: "staff", label: "Administration", section: "/staff", detail: false },
  { route: "/staff/assessments", area: "staff", label: "Assessments", section: "/staff", detail: false },
  { route: "/staff/assessments/marksheet", area: "staff", label: "Marksheet", section: "/staff/assessments", detail: false },
  { route: "/staff/attendance", area: "staff", label: "Attendance", section: "/staff", detail: false },
  { route: "/staff/calendar", area: "staff", label: "Calendar", section: "/staff", detail: false },
  { route: "/staff/classes", area: "staff", label: "Classes", section: "/staff", detail: false },
  { route: "/staff/communication", area: "staff", label: "Communication", section: "/staff", detail: false },
  { route: "/staff/communication/exam-results", area: "staff", label: "Exam Results", section: "/staff/communication", detail: false },
  { route: "/staff/communication/groups", area: "staff", label: "Groups", section: "/staff/communication", detail: false },
  { route: "/staff/communication/templates", area: "staff", label: "Templates", section: "/staff/communication", detail: false },
  { route: "/staff/departments", area: "staff", label: "Departments", section: "/staff", detail: false },
  { route: "/staff/directory", area: "staff", label: "Directory", section: "/staff", detail: false },
  { route: "/staff/finance", area: "staff", label: "Finance", section: "/staff", detail: false },
  { route: "/staff/finance/analysis", area: "staff", label: "Analysis", section: "/staff/finance", detail: false },
  { route: "/staff/finance/debtors", area: "staff", label: "Debtors", section: "/staff/finance", detail: false },
  { route: "/staff/finance/expenses", area: "staff", label: "Expenses", section: "/staff/finance", detail: false },
  { route: "/staff/finance/expenses/[itemId]", area: "staff", label: "Item detail", section: "/staff/finance", detail: true },
  { route: "/staff/finance/fee-structures", area: "staff", label: "Fee Structures", section: "/staff/finance", detail: false },
  { route: "/staff/finance/ledger", area: "staff", label: "Ledger", section: "/staff/finance", detail: false },
  { route: "/staff/finance/payments", area: "staff", label: "Payments", section: "/staff/finance", detail: false },
  { route: "/staff/finance/reconciliation", area: "staff", label: "Reconciliation", section: "/staff/finance", detail: false },
  { route: "/staff/finance/reports", area: "staff", label: "Reports", section: "/staff/finance", detail: false },
  { route: "/staff/finance/settings", area: "staff", label: "Settings", section: "/staff/finance", detail: false },
  { route: "/staff/finance/setup", area: "staff", label: "Setup", section: "/staff/finance", detail: false },
  { route: "/staff/finance/students", area: "staff", label: "Students", section: "/staff/finance", detail: false },
  { route: "/staff/finance/students/[studentId]", area: "staff", label: "Student detail", section: "/staff/finance", detail: true },
  { route: "/staff/finance/terms", area: "staff", label: "Terms", section: "/staff/finance", detail: false },
  { route: "/staff/finance/transactions", area: "staff", label: "Transactions", section: "/staff/finance", detail: false },
  { route: "/staff/history", area: "staff", label: "History", section: "/staff", detail: false },
  { route: "/staff/library", area: "staff", label: "Library", section: "/staff", detail: false },
  { route: "/staff/library/analytics", area: "staff", label: "Analytics", section: "/staff/library", detail: false },
  { route: "/staff/library/analytics/books", area: "staff", label: "Books", section: "/staff/library", detail: false },
  { route: "/staff/library/analytics/borrowing", area: "staff", label: "Borrowing", section: "/staff/library", detail: false },
  { route: "/staff/library/analytics/fines", area: "staff", label: "Fines", section: "/staff/library", detail: false },
  { route: "/staff/library/analytics/inventory", area: "staff", label: "Inventory", section: "/staff/library", detail: false },
  { route: "/staff/library/analytics/reports", area: "staff", label: "Reports", section: "/staff/library", detail: false },
  { route: "/staff/library/analytics/students", area: "staff", label: "Students", section: "/staff/library", detail: false },
  { route: "/staff/library/cards", area: "staff", label: "Cards", section: "/staff/library", detail: false },
  { route: "/staff/library/catalogue", area: "staff", label: "Catalogue", section: "/staff/library", detail: false },
  { route: "/staff/library/circulate", area: "staff", label: "Circulate", section: "/staff/library", detail: false },
  { route: "/staff/library/copies", area: "staff", label: "Copies", section: "/staff/library", detail: false },
  { route: "/staff/library/fines", area: "staff", label: "Fines", section: "/staff/library", detail: false },
  { route: "/staff/library/inventory", area: "staff", label: "Inventory", section: "/staff/library", detail: false },
  { route: "/staff/library/inventory/[id]", area: "staff", label: " detail", section: "/staff/library", detail: true },
  { route: "/staff/library/inventory/[id]/qr", area: "staff", label: "Qr", section: "/staff/library", detail: false },
  { route: "/staff/library/issue", area: "staff", label: "Issue", section: "/staff/library", detail: false },
  { route: "/staff/library/lending", area: "staff", label: "Lending", section: "/staff/library", detail: false },
  { route: "/staff/library/policies", area: "staff", label: "Policies", section: "/staff/library", detail: false },
  { route: "/staff/library/reservations", area: "staff", label: "Reservations", section: "/staff/library", detail: false },
  { route: "/staff/library/return", area: "staff", label: "Return", section: "/staff/library", detail: false },
  { route: "/staff/library/scan", area: "staff", label: "Scan", section: "/staff/library", detail: false },
  { route: "/staff/library/setup", area: "staff", label: "Setup", section: "/staff/library", detail: false },
  { route: "/staff/people", area: "staff", label: "People", section: "/staff", detail: false },
  { route: "/staff/profile", area: "staff", label: "Profile", section: "/staff", detail: false },
  { route: "/staff/records", area: "staff", label: "Records", section: "/staff", detail: false },
  { route: "/staff/records/achievements", area: "staff", label: "Achievements", section: "/staff/records", detail: false },
  { route: "/staff/records/discipline", area: "staff", label: "Discipline", section: "/staff/records", detail: false },
  { route: "/staff/reports", area: "staff", label: "Reports", section: "/staff", detail: false },
  { route: "/staff/students", area: "staff", label: "Students", section: "/staff", detail: false },
  { route: "/staff/students/[id]", area: "staff", label: " detail", section: "/staff/students", detail: true },
  { route: "/staff/subjects", area: "staff", label: "Subjects", section: "/staff", detail: false },
  { route: "/staff/timetable", area: "staff", label: "Timetable", section: "/staff", detail: false },
  { route: "/staff/timetable/builder", area: "staff", label: "Builder", section: "/staff/timetable", detail: false },
  { route: "/staff/timetable/generate", area: "staff", label: "Generate", section: "/staff/timetable", detail: false },
  { route: "/staff/timetable/preferences", area: "staff", label: "Preferences", section: "/staff/timetable", detail: false },
  { route: "/staff/timetable/requirements", area: "staff", label: "Requirements", section: "/staff/timetable", detail: false },
  { route: "/staff/timetable/settings", area: "staff", label: "Settings", section: "/staff/timetable", detail: false },
  { route: "/staff/timetable/template", area: "staff", label: "Template", section: "/staff/timetable", detail: false },
  { route: "/staff/timetable/versions", area: "staff", label: "Versions", section: "/staff/timetable", detail: false },
  { route: "/staff/tod", area: "staff", label: "TOD", section: "/staff", detail: false },
  { route: "/teacher", area: "teacher", label: "Dashboard (home)", section: "/teacher", detail: false },
  { route: "/teacher/academics", area: "teacher", label: "Academics", section: "/teacher", detail: false },
  { route: "/teacher/academics/classes", area: "teacher", label: "Classes", section: "/teacher/academics", detail: false },
  { route: "/teacher/academics/departments", area: "teacher", label: "Departments", section: "/teacher/academics", detail: false },
  { route: "/teacher/academics/subjects", area: "teacher", label: "Subjects", section: "/teacher/academics", detail: false },
  { route: "/teacher/accommodation", area: "teacher", label: "Accommodation", section: "/teacher", detail: false },
  { route: "/teacher/accommodation-details", area: "teacher", label: "Accommodation Details", section: "/teacher", detail: false },
  { route: "/teacher/accommodation-details/analytics", area: "teacher", label: "Analytics", section: "/teacher/accommodation-details", detail: false },
  { route: "/teacher/accommodation-details/dormitories/[dormId]", area: "teacher", label: "Dorm detail", section: "/teacher/accommodation-details", detail: true },
  { route: "/teacher/assessments", area: "teacher", label: "Assessments", section: "/teacher", detail: false },
  { route: "/teacher/assessments/dashboard", area: "teacher", label: "Dashboard", section: "/teacher/assessments", detail: false },
  { route: "/teacher/assessments/dept-analytics", area: "teacher", label: "Dept Analytics", section: "/teacher/assessments", detail: false },
  { route: "/teacher/assessments/marksheet", area: "teacher", label: "Marksheet", section: "/teacher/assessments", detail: false },
  { route: "/teacher/assessments/ranking", area: "teacher", label: "Ranking", section: "/teacher/assessments", detail: false },
  { route: "/teacher/assessments/report-cards", area: "teacher", label: "Report Cards", section: "/teacher/assessments", detail: false },
  { route: "/teacher/assessments/report-cards/[studentId]", area: "teacher", label: "Student detail", section: "/teacher/assessments", detail: true },
  { route: "/teacher/assessments/settings", area: "teacher", label: "Settings", section: "/teacher/assessments", detail: false },
  { route: "/teacher/attendance", area: "teacher", label: "Attendance", section: "/teacher", detail: false },
  { route: "/teacher/calendar", area: "teacher", label: "Calendar", section: "/teacher", detail: false },
  { route: "/teacher/communication", area: "teacher", label: "Communication", section: "/teacher", detail: false },
  { route: "/teacher/communication/exam-results", area: "teacher", label: "Exam Results", section: "/teacher/communication", detail: false },
  { route: "/teacher/communication/groups", area: "teacher", label: "Groups", section: "/teacher/communication", detail: false },
  { route: "/teacher/communication/templates", area: "teacher", label: "Templates", section: "/teacher/communication", detail: false },
  { route: "/teacher/diary", area: "teacher", label: "Diary", section: "/teacher", detail: false },
  { route: "/teacher/diary/[id]", area: "teacher", label: " detail", section: "/teacher/diary", detail: true },
  { route: "/teacher/history", area: "teacher", label: "History", section: "/teacher", detail: false },
  { route: "/teacher/people", area: "teacher", label: "People", section: "/teacher", detail: false },
  { route: "/teacher/people/[tileId]", area: "teacher", label: "Tile detail", section: "/teacher/people", detail: true },
  { route: "/teacher/profile", area: "teacher", label: "Profile", section: "/teacher", detail: false },
  { route: "/teacher/records", area: "teacher", label: "Records", section: "/teacher", detail: false },
  { route: "/teacher/records/achievements", area: "teacher", label: "Achievements", section: "/teacher/records", detail: false },
  { route: "/teacher/records/discipline", area: "teacher", label: "Discipline", section: "/teacher/records", detail: false },
  { route: "/teacher/records/discipline/[id]", area: "teacher", label: " detail", section: "/teacher/records", detail: true },
  { route: "/teacher/results", area: "teacher", label: "Results", section: "/teacher", detail: false },
  { route: "/teacher/results/slips", area: "teacher", label: "Slips", section: "/teacher/results", detail: false },
  { route: "/teacher/students", area: "teacher", label: "Students", section: "/teacher", detail: false },
  { route: "/teacher/students/[id]", area: "teacher", label: " detail", section: "/teacher/students", detail: true },
  { route: "/teacher/timetable", area: "teacher", label: "Timetable", section: "/teacher", detail: false },
];
