/**
 * InvoiceList — renders parent-visible fee invoices as a card list.
 * Empty state shown when no invoices exist.
 *
 * Requirements: 7.3
 */

import { FileText } from "lucide-react";

export interface InvoiceItem {
  id: string;
  invoiceNumber: string;
  totalAmount: number;
  generatedAt: string | Date;
  termName?: string | null;
}

interface InvoiceListProps {
  invoices: InvoiceItem[];
}

function formatDate(value: string | Date): string {
  const d = typeof value === "string" ? new Date(value) : value;
  return d.toLocaleDateString("en-KE", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });
}

function formatKsh(value: number): string {
  return new Intl.NumberFormat("en-KE", {
    style:                 "currency",
    currency:              "KES",
    minimumFractionDigits: 2,
  }).format(Math.abs(value));
}

export default function InvoiceList({ invoices }: InvoiceListProps) {
  if (invoices.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center py-12 text-center">
        <FileText className="h-10 w-10 text-slate dark:text-dark-muted mb-3" />
        <p className="text-sm font-semibold text-ink dark:text-dark-text">
          No invoices on record.
        </p>
        <p className="text-xs text-slate dark:text-dark-muted mt-1">
          Fee invoices will appear here once generated by the bursar.
        </p>
      </div>
    );
  }

  return (
    <div className="space-y-2">
      {invoices.map((invoice) => (
        <div
          key={invoice.id}
          className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-2 sm:gap-3 rounded-xl border border-line
                     bg-card px-4 py-3 shadow-xs dark:bg-dark-surface dark:border-dark-border"
        >
          <div className="flex items-center gap-3 min-w-0">
            <div className="w-8 h-8 rounded-lg bg-info/10 flex items-center justify-center shrink-0">
              <FileText className="h-4 w-4 text-info" />
            </div>
            <div className="min-w-0">
              <p className="text-sm font-semibold text-ink dark:text-dark-text truncate">
                {invoice.invoiceNumber}
              </p>
              <p className="text-xs text-slate dark:text-dark-muted">
                {invoice.termName ? `${invoice.termName} · ` : ""}
                {formatDate(invoice.generatedAt)}
              </p>
            </div>
          </div>
          <p className="text-sm font-bold text-ink dark:text-dark-text shrink-0">
            {formatKsh(invoice.totalAmount)}
          </p>
        </div>
      ))}
    </div>
  );
}
