import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { requireRecordsPermission } from "@/lib/permissions";
import { emitSSE } from "@/lib/sse";

const createSchema = z.object({
  studentId: z.string().min(1),
  offence: z.string().trim().min(2, "Enter the offence."),
  description: z.string().trim().optional().or(z.literal("")),
  actionTaken: z.string().trim().optional().or(z.literal("")),
  dateOfOffence: z.string().min(1, "Enter the date of the offence."),
  status: z.enum(["OPEN", "UNDER_REVIEW", "RESOLVED", "ESCALATED"]).optional(),
  notes: z.string().trim().optional().or(z.literal("")),
  // Optional AI summary already generated by /api/discipline/suggest —
  // saved with the record so no second AI call is needed.
  aiSummary: z.string().trim().max(300).optional().or(z.literal("")),
});

export async function GET(req: NextRequest) {
  const user = await requireRecordsPermission("RECORDS_DISCIPLINE", "view");
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const studentId = req.nextUrl.searchParams.get("studentId") || undefined;
  const records = await prisma.disciplineRecord.findMany({
    where: { schoolId: user.schoolId!, ...(studentId ? { studentId } : {}) },
    orderBy: { dateOfOffence: "desc" },
    include: {
      student: { select: { id: true, fullName: true, admissionNumber: true, schoolClass: { select: { id: true, name: true, form: true, stream: true } } } },
      recordedBy: { select: { email: true, role: true, teacher: { select: { fullName: true } } } },
      _count: { select: { files: true, caseNotes: true } },
    },
  });
  return NextResponse.json(records);
}

export async function POST(req: NextRequest) {
  const user = await requireRecordsPermission("RECORDS_DISCIPLINE", "manage");
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const parsed = createSchema.safeParse(await req.json().catch(() => null));
  if (!parsed.success) {
    return NextResponse.json(
      { error: parsed.error.errors[0]?.message || "Invalid input." },
      { status: 400 }
    );
  }
  const d = parsed.data;

  const student = await prisma.student.findFirst({
    where: { id: d.studentId, schoolId: user.schoolId! },
    select: { id: true, classId: true },
  });
  if (!student) return NextResponse.json({ error: "Student not found." }, { status: 404 });

  try {
    const record = await prisma.disciplineRecord.create({
      data: {
        schoolId: user.schoolId!,
        studentId: student.id,
        classId: student.classId,
        offence: d.offence,
        description: d.description || null,
        actionTaken: d.actionTaken || null,
        dateOfOffence: new Date(d.dateOfOffence),
        status: d.status || "OPEN",
        notes: d.notes || null,
        aiSummary: d.aiSummary || null,
        recordedById: user.id,
        events: {
          create: { type: "CREATED", detail: `Case opened: ${d.offence}`, createdById: user.id },
        },
      },
    });
    emitSSE(user.schoolId!, "disciplineRecord.created", record);
    return NextResponse.json(record, { status: 201 });
  } catch {
    return NextResponse.json({ error: "Couldn't record the discipline case." }, { status: 500 });
  }
}
